# Generated by Django 4.2.1 on 2023-07-07 20:35

import announcements.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('header', models.CharField(default='', max_length=64, verbose_name='Заголовок')),
                ('main_text', models.TextField(default='', verbose_name='Текст объявления')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=announcements.models.get_av_path, verbose_name='Аватар')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('announcement', models.ManyToManyField(related_name='files', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True, verbose_name='Категория')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribing_categories', to='announcements.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_categories', to='announcements.announcement')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_of_announcements', to='announcements.category')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_announcements', to='announcements.profile', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ManyToManyField(through='announcements.AnnouncementCategory', to='announcements.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ANCTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_date', models.DateField(auto_now_add=True)),
                ('message', models.TextField(default='')),
                ('confirm', models.BooleanField(default=False)),
                ('refuse', models.BooleanField(default=False)),
                ('announcement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='anctresponses', to='announcements.announcement')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='announcements.profile')),
                ('buyer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='announcements.profile')),
            ],
        ),
    ]
